language: swift
xcode_project: App2WebHandoff.xcodeproj
xcode_scheme: App2WebHandoff

osx_image: xcode9
xcode_sdk: iphonesimulator11.0

script:
- xcodebuild -project App2WebHandoff.xcodeproj -scheme App2WebHandoff -sdk iphonesimulator11.0 -destination "platform=iOS Simulator,name=iPhone 7,OS=11.0" -configuration Debug -enableCodeCoverage YES clean build test

after_success:
- bash <(curl -s https://codecov.io/bash)
