language: objective-c
xcode_project: App2WebHandoff.xcodeproj
xcode_scheme: App2WebHandoff

osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

script:
- xcodebuild -project App2WebHandoff.xcodeproj -scheme App2WebHandoff -sdk iphonesimulator10.2 -destination "platform=iOS Simulator,name=iPhone 7,OS=10.1" -configuration Debug -enableCodeCoverage YES clean build test